name: 'Lint PR Title'
on:
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  main:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: release-please-plus/action-lint-pr-title@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
